### ISSUE TITLE
qhull input error for hxk4_bs.mol2

### ISSUE THREAD

**Issue by shahrzad** [CSBG-LSU/bionoi#7]
I get this error when I want to generate the voronoi image for ```hxk4_bs.mol2``` file.
```
./voronoi.py:119: RuntimeWarning: divide by zero encountered in double_scalars
  def voronoi_atoms(bs, cmap, bs_out=None, size=None, dpi=None, alpha=0.5, save_fig=True, projection=lambda a,b: a/abs(b)**.5):
Traceback (most recent call last):
  File "./voronoi.py", line 218, in <module>
    atoms, vor, img = Bionoi(args.mol, args.cmap, args.out, args.size, args.dpi, args.alpha)
  File "./voronoi.py", line 210, in Bionoi
    atoms, vor, img = voronoi_atoms(mol, cmap, bs_out=bs_out, size=size, dpi=dpi, alpha=alpha, save_fig=True)
  File "./voronoi.py", line 146, in voronoi_atoms
    vor = Voronoi(atoms[['P(x)','P(y)']])
  File "qhull.pyx", line 2494, in scipy.spatial.qhull.Voronoi.__init__
  File "qhull.pyx", line 354, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH6019 qhull input error: can not scale last coordinate.  Input is cocircular
   or cospherical.   Use option 'Qz' to add a point at infinity.

While executing:  | qhull v Qz Qbb Qc
Options selected for Qhull 2015.2.r 2016/01/18:
  run-id 794730633  voronoi  Qz-infinity-point  Qbbound-last  Qcoplanar-keep
  _pre-merge  _zero-centrum  Qinterior-keep  Pgood

```
Also my generated images still look like before, for example for cah2_bs.mol2 it looks like this:
![cah2](https://user-images.githubusercontent.com/9300882/47038559-63ad8700-d147-11e8-9847-41a278c040d1.png)

**Comment by jeffmylife** [comment]
Can you provide the hxk4_bs.mol2 and the cah2_bs.mol2 file you're using? It'll be easier to fix. You can attach the files here.

**Comment by shahrzad** [comment]
Sure. It only allowed me to do it as a zip file though since it was a  .mol2 file.

[mols.zip](https://github.com/CSBG-LSU/bionoi/files/2484553/mols.zip)

**Comment by jeffmylife** [comment]
I fixed the bug causing qhull error for hxk4_bs.mol2. It arose from the projection function creating a div by zero error. See commit [46af037](https://github.com/CSBG-LSU/bionoi/commit/46af0379e318a30078d5f93a67e85aa3a1af1d8f) if interested. 

The reason cah2_bs.mol2 is doing this is because of the pocket's complex 3D geometry. Here's a picture of it: 

![screen shot 2018-10-16 at 8 17 24 pm](https://user-images.githubusercontent.com/25440288/47056161-b2c3de00-d180-11e8-8d2e-0cb3b9f4f82a.png)
You see that there's not a simple 2D 'face' of the pocket that we can project. 
For now, don't worry about it. We'll address these issues later.

**Comment by shahrzad** [comment]
OK, thank you so much.
